name: Stove Heating AI
version: "1.3.0"
slug: stove_heating_ai
description: AI model for stove heating prediction and control
url: "https://github.com/sibest19/ha-addons/tree/main/stove_heating_ai"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  influxdb_host: ""
  influxdb_port: 8086
  influxdb_user: ""
  influxdb_password: ""
schema:
  influxdb_host: str
  influxdb_port: "int?"
  influxdb_user: str
  influxdb_password: password
ports:
  "8099/tcp": null
ports_description:
  "8099/tcp": Web UI and API
ingress: true
apparmor: false
image: "ghcr.io/sibest19/{arch}-addon-stove-heating-ai"
panel_icon: mdi:fire
